### ISSUE TITLE
HubAlign not working with example files

### ISSUE THREAD

**Issue by tropicalberto** [hashemifar/HubAlign#2]
I am trying to run HubAlign with the default parameters that you give (./HubAlign example/Test1.tab example/Test2.tab –l 0.1 –a 0.7 –d 10 –b similarityFile.txt), and with the example files from the repo, but I don't manage to do it, I always get the same error: 

> 4411
> Error in argument : –l

I compiled the executable file using g++ (g++ HubAlign.cpp Alignment.cpp Network.cpp -o HubAlign).

I have also tried with the HubAlign version that can be found in your webpage [http://ttic.uchicago.edu/%7Ehashemifar/ ](http://ttic.uchicago.edu/%7Ehashemifar/) but I encountered the same errors. Trying with different combinations of parameters is also not working.

Do you have any tips about what I might be doing wrong? Thank you!

**Comment by hashemifar** [comment]
Dear Alberto,

Do you type the command yourself or copy-paste it?!!!
I think you do copy-paste and that is why you get an error!!

Please type the command yourself and see how it goes.
Let me know how it goes.

Best,
Somaye

**Comment by hashemifar** [comment]
Also please check the name of the SimilarityFile in your folder. is it
named  Test1_Test2.bitscore or similarityFile.txt? and the correct name.

Best,
Somaye

**Comment by tropicalberto** [comment]
Hi Somaye, 

indeed, I did not type properly the similarity file name! (I just thought that it was the name of the output file, and not the file with the BLAST scores, that is why I just copied pasted that name. sorry for not properly reading the readme).

Thanks a lot for your work! 
Alberto
